import FarmerSideBar from "@/components/farmer/FarmerSideBar";
import FarmerTopBar from "@/components/farmer/FarmerTopBar";
import { getUser } from "@/components/supabase/GetUser";
import type { Metadata } from "next";
import { Quicksand } from "next/font/google";

export const metadata: Metadata = {
  title: "DairyLink",
  description: "Generated by create next app",
};

const quickSand = Quicksand({
  subsets: ["latin"],
  variable: "--font-quickSand",
});

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await getUser();

  return (
      <div className={`text-white ${quickSand.variable}`}>
        <div>
          <FarmerTopBar user={user} />
          <div className="flex flex-row">
            <FarmerSideBar />
            <div className="flex min-h-screen flex-1 flex-col items-center bg-customDark w-full">
              <div className="p-4">{children}</div>
            </div>
          </div>
        </div>
      </div>
  );
}
