import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import TopBar from "@/components/shared/TopBar";
import Footer from "@/components/shared/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "DairyLink",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`m-8 ${inter.className}`}>
        <main>
          <section>
            <TopBar />
            <div>
              {children}
            </div>
          </section>
        </main>
        <Footer />
      </body>
    </html>
  );
}
