import Footer from "@/components/shared/Footer";
import TopBar from "@/components/shared/TopBar";
import type { Metadata } from "next";
import { Inter, Quicksand, Tinos } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
const quickSand = Quicksand({
  subsets: ["latin"],
  variable: "--font-quickSand",
});
const tinos = Tinos({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-tinos",
});

export const metadata: Metadata = {
  title: "DairyLink",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${quickSand.variable}`}>
        <main>
          <section>
            <TopBar />
            <div>{children}</div>
          </section>
        </main>
        <Footer />
      </body>
    </html>
  );
}
